using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Generate_name : MonoBehaviour
{
    public TextMesh NameText;
    void Start () {
        string[] biomes = new string[] { 
            "Neo", 
            "BanyaponP", 
            "JennyMango", 
            "rocky", 
            "swamp", 
            "tundra",
            "Gafild",
            "มะยงชิท",
            "กิตติศักดิ์",
            "Kylie",
            "Cortney",
            "Dario",
            "Maryann",
            "Harvey",
            "Guy",
            "Janessa",
            "Averie",
            "Cecelia",
            "Laken",
            "Julian",
            "Alli",
            "Anabel",
            "Marcellus",
            "Janell",
            "Kori",
            "Tyana",
            "Meghan",
            "Montserrat",
            "Neal",
            "Jane",
            "Bryanna",
            "Vera",
            "Braden",
            "Taniya",
            "Ernest",
            "Camden",
            "Deshaun",
            "Travis",
            "Peyton",
            "Alexi",
            "Sage",
            "Miltoz",
            "Carlton",
            "Slade",
            "Anika",
            "Willie",
            "Demetrius",
            "Jordi",
            "Bridget",
            "Celine",
            "Messiah",
            "Emma",
            "Antonia",
            "Alvaro",
            "Jace",
            "Jessalyn",
            "Abel",
            "Laura",
            "Kaden",
            "Marlene",
            "Shea",
            "Austin",
            "Arthur",
            "Oliver",
            "James",
            "Katheryn",
            "Jaya",
            "Yessenia",
            "Chance",
            "Kegan",
            "Jean",
            "Claire",
            "Ileana",
            "China",
            "Deshaun",
            "Mercy",
            "Armando",
            "Whitney",
            "Lewis",
            "Vera",
            "Galen",
            "Jaron",
            "Anabel",
            "Carmen",
            "Omari",
            "Deasia",
            "Yousef",
            "Tyriq",
            "Braydon",
            "Reyna",
            "Jazmyn",
            "Ulysses",
            "Robyn",
            "Mary",
            "Michael",
            "Mariana",
            "Elizabeth",
            "Aaron",
            "Anjelica",
            "Brynn",
            "Luiz",
            "Amari",
            "Demi",
            "Kiera",
            "Kiley",
            "Vivian",
            "Kallie",
            "Sammy",
            "Pierce",
            "อำนวย คยหย่าย",
            "Prawit Chanocha"
            };
        System.Random random = new System.Random();
        int useBiome = random.Next (biomes.Length);
        string pickBiome = biomes[useBiome];
        NameText.text =""+pickBiome;
    }
}
